# Generated by Django 3.0.2 on 2020-01-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False, unique=True)),
                ('emailAddress', models.TextField()),
                ('timeFrameBegin', models.DateTimeField()),
                ('dateOfRegistration', models.DateTimeField(auto_now=True)),
                ('adultsCount', models.IntegerField()),
                ('childCount', models.IntegerField()),
                ('state', models.CharField(max_length=120)),
            ],
        ),
    ]
