# Generated by Django 3.0.2 on 2020-03-07 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OsterAnmeldung', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='adultsCount',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='childCount',
        ),
    ]
